source 'https://rubygems.org'

gem 'rails', '5.2.6.3'
gem 'json'
gem 'bootsnap', require: false
gem 'webpacker', git: 'https://github.com/YuriiRudenko/webpacker_without_compile.git'
gem 'puma', '>= 5.6.4'
gem 'activeresource' , require: 'active_resource'
gem 'sass-rails'
gem 'haml-rails'
gem 'grape'
gem 'grape-entity'
gem 'interactor-contracts'
gem 'interactor-rails'
gem 'terser'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'rails4-autocomplete'
gem 'turbolinks'
gem 'cocoon'
gem 'jbuilder'
group :doc do
  gem 'sdoc', require: false
end
gem 'best_in_place', '~> 3.0.1'
gem 'mini_racer', '~> 0.3.1', platforms: :ruby
gem 'twitter-bootstrap-rails', '2.2.7'
gem 'bson'
gem 'devise'
gem 'omniauth-google-oauth2', '>= 0.8.0'
gem 'omniauth', '1.9.1'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-oauth2'
gem 'kaminari-mongoid'
gem 'mongoid', '6.4'
gem 'mongoid-paperclip', :require => 'mongoid_paperclip'
gem 'paperclip', '>= 5.2.0'
gem 'jquery-fileupload-rails'
gem 'kaminari'
gem 'kaminari-bootstrap'
gem 'mandrill-api-json'
gem 'rolify'
gem 'sidekiq'
gem 'redis', '< 4.6'
gem 'sidekiq-failures'
gem 'jira-api-wrapper', git: 'https://lab.mocintra.com/gems/jira-api-wrapper', :tag => 'v0.4.0'
gem 'mongoid_search', git: 'https://lab.mocintra.com/gems/mongoid_search'
gem 'mongoid_taggable_with_context'
gem 'font-awesome-rails'
gem 'mongoid-history'
gem 'mongoid_paranoia'
gem 'gibberish'
gem 'mongoid-encrypted-fields'
gem 'diffy'
gem 'rails_autolink'
gem 'business_time'
gem 'google_drive'
gem 'select2-rails'
gem 'axlsx'
gem 'rubocop'
gem 'docx_replace'
gem 'zip-zip'
gem 'httparty'
gem 'multiverse'
gem 'activerecord'
gem 'pg', '~> 0.21'
gem 'money-rails'
gem 'gon'
gem 'airbrake'
gem 'groupdate'
gem 'strip_attributes'

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'rspec'
  gem 'rspec-grape'
  gem 'rspec-rails'
end

group :development do
  gem 'awesome_print'
  gem 'better_errors'
  gem 'passenger-rails'
  # gem 'quiet_assets'
  gem 'annotate'
  gem 'flamegraph'
  gem 'stackprof'
  # gem 'rack-mini-profiler'
  gem 'grape_on_rails_routes'
  gem 'pry-byebug'
  gem 'pry-rails'
  # gem 'i18n', '~>0.7.0'
  gem 'lograge'
  # gem 'gelf'
  gem 'bullet'
end

group :development, :staging, :pre_production do
  gem 'faker'
  gem 'letter_opener_web'
end
