version: "2"
services:

#  proxy:
#    image: nginx:stable-alpine
#    container_name: 'proxy'
#    restart: always
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - /etc/letsencrypt/archive:/etc/nginx/ssl/archive
#      - /etc/letsencrypt/live:/etc/nginx/ssl/live
#      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#      - ./logs:/var/log/nginx:rw
#    links:
#      - hrdev:hrdev
#    tty: true

  hrdev:
    image: 320485110145.dkr.ecr.eu-west-3.amazonaws.com/hr_module_bookkeeping.production
    container_name: 'hrdev'
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./.env.production
    command: /bin/sh -c "puma -t 2:4 -b tcp://0.0.0.0:3000 && bundle exec sidekiq -d -L log/sidekiq.log -C config/sidekiq.yml -e production"
    tty: true
    volumes:
      - ./config/secrets.yml:/myapp/config/secrets.yml
      - ./config/database.yml:/myapp/config/database.yml
      - ./config/external_services:/myapp/config/external_services
      - ./logs:/myapp/log:rw
      - ./photos:/myapp/public/system/users/photos:rw
